In [ ]:
pip install pandas_ods_reader

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandas_ods_reader
  Downloading pandas_ods_reader-0.1.4-py3-none-any.whl (6.7 kB)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from pandas_ods_reader) (1.4.4)
Requirement already satisfied: lxml<5.0.0,>=4.6.3 in /usr/local/lib/python3.9/dist-packages (from pandas_ods_reader) (4.9.2)
Collecting ezodf<0.4.0,>=0.3.2
  Downloading ezodf-0.3.2.tar.gz (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.9/125.9 KB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas<2.0.0,>=1.0.0->pandas_ods_reader) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas<2.0.0,>=1.0.0->pandas_ods_reader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas<2.0.0,>=1.0.0->pandas_ods_reader) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->pandas_ods_reader) (1.16.0)
Building wheels for collected packages: ezodf
  Building wheel for ezodf (setup.py) ... done
  Created wheel for ezodf: filename=ezodf-0.3.2-py2.py3-none-any.whl size=49002 sha256=f6cbe9dbb66ef3fdd57353925909d4139f6a80d5ff42797c6f6f0c7acaa56582
  Stored in directory: /root/.cache/pip/wheels/d0/0e/c2/1af349f0c9e110ed08133a3d579f402f3ec1c031eac80bc084
Successfully built ezodf
Installing collected packages: ezodf, pandas_ods_reader
Successfully installed ezodf-0.3.2 pandas_ods_reader-0.1.4

In [ ]:
import pandas_ods_reader as pd

In [ ]:

base = pd.read_ods('dados_roubo.ods')

In [ ]:
base
#Base de Dados Original

,ANO_BO,NUM_BO,NUMERO_BOLETIM,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,HORAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,...,TIPOVINCULO,RELACIONAMENTO,PARENTESCO,PLACA_VEICULO,UF_VEICULO,CIDADE_VEICULO,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO
0,2023.0,8696.0,8696/2023,01/01/2023 01:23:54,01/01/2023 01:23:58,31/12/2022,22:20,A NOITE,31/12/2022,01/01/2023 01:23:54,...,None,None,None,None,None,FXZ3H05,SP,S.PAULO,Preta,HONDA/FIT EXL CVT
1,2023.0,70.0,70/2023,01/01/2023 01:31:03,01/01/2023 01:31:03,31/12/2022,15:54,A TARDE,31/12/2022,01/01/2023 01:31:03,...,None,None,None,None,None,FKV8033,SP,S.PAULO,Preta,I/HONDA CR-V EXL FLEX4WD
2,2023.0,11.0,11/2023,01/01/2023 01:44:06,01/01/2023 01:44:06,31/12/2022,23:45,A NOITE,01/01/2023,01/01/2023 01:44:06,...,None,None,None,None,None,BVT0G14,SP,DIADEMA,Branco,RENAULT/KWID ZEN 10MT
3,2023.0,8746.0,8746/2023,01/01/2023 02:06:13,01/01/2023 02:06:15,31/12/2022,22:30,A NOITE,01/01/2023,01/01/2023 02:06:13,...,None,None,None,None,None,ECH1F98,SP,S.ANDRE,Vermelho,YAMAHA/FAZER YS250
4,2023.0,8756.0,8756/2023,01/01/2023 02:23:39,01/01/2023 02:23:43,31/12/2022,22:20,A NOITE,01/01/2023,01/01/2023 02:23:39,...,None,None,None,None,None,FIG8B56,SP,FERRAZ DE VASCONCELO,Vermelho,VW/FOX CONNECT MB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12976,2023.0,552.0,552/2023,31/01/2023 23:05:38,31/01/2023 23:05:38,31/01/2023,19:40,A NOITE,31/01/2023,31/01/2023 23:05:38,...,None,None,None,None,None,RMT7A75,MG,BELO HORIZONTE,Prata,VW/VOYAGE PLUS
12977,2023.0,170023.0,170023/2023,31/01/2023 23:07:03,31/01/2023 23:07:06,31/01/2023,20:17,A NOITE,31/01/2023,31/01/2023 23:07:03,...,None,None,None,None,None,EBG3309,SP,S.PAULO,Amarelo,FIAT/STILO SPORTING DUAL
12978,2023.0,982.0,982/2023,31/01/2023 23:28:40,31/01/2023 23:28:40,31/01/2023,22:25,A NOITE,31/01/2023,31/01/2023 23:28:40,...,None,None,None,None,None,FUF5D21,SP,S.PAULO,Vermelho,HONDA/CG 160 FAN
12979,2023.0,170179.0,170179/2023,31/01/2023 23:47:30,31/01/2023 23:47:33,31/01/2023,21:10,A NOITE,31/01/2023,31/01/2023 23:47:30,...,None,None,None,GAZ8339,SP,ARUJA,Branco,HONDA/CIVIC EX CVT,2017.0,None
12980,2023.0,170223.0,170223/2023,31/01/2023 23:57:24,31/01/2023 23:57:28,31/01/2023,19:55,A NOITE,31/01/2023,31/01/2023 23:57:24,...,None,None,None,GCX3195,SP,S.PAULO,Cinza,FORD/KA,2019.0,None

Warning: Total number of columns (51) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
import numpy as np

In [ ]:
 base.pop("unnamed.1")
 base.pop("unnamed.2")
 base.pop("QUANT_CELULAR")
 base.pop("MARCA_CELULAR")
 base.pop("DESCR_TIPO_VEICULO") 
 #Remoção de algumas colunas

In [ ]:
base
# Nova Base

,ANO_BO,NUM_BO,NUMERO_BOLETIM,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,HORAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,...,RELACIONAMENTO,PARENTESCO,PLACA_VEICULO,UF_VEICULO,CIDADE_VEICULO,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,DESCR_TIPO_VEICULO
0,2023.0,8696.0,8696/2023,01/01/2023 01:23:54,01/01/2023 01:23:58,31/12/2022,22:20,A NOITE,31/12/2022,01/01/2023 01:23:54,...,None,None,None,None,FXZ3H05,SP,S.PAULO,Preta,HONDA/FIT EXL CVT,2021.0
1,2023.0,70.0,70/2023,01/01/2023 01:31:03,01/01/2023 01:31:03,31/12/2022,15:54,A TARDE,31/12/2022,01/01/2023 01:31:03,...,None,None,None,None,FKV8033,SP,S.PAULO,Preta,I/HONDA CR-V EXL FLEX4WD,2013.0
2,2023.0,11.0,11/2023,01/01/2023 01:44:06,01/01/2023 01:44:06,31/12/2022,23:45,A NOITE,01/01/2023,01/01/2023 01:44:06,...,None,None,None,None,BVT0G14,SP,DIADEMA,Branco,RENAULT/KWID ZEN 10MT,2019.0
3,2023.0,8746.0,8746/2023,01/01/2023 02:06:13,01/01/2023 02:06:15,31/12/2022,22:30,A NOITE,01/01/2023,01/01/2023 02:06:13,...,None,None,None,None,ECH1F98,SP,S.ANDRE,Vermelho,YAMAHA/FAZER YS250,2008.0
4,2023.0,8756.0,8756/2023,01/01/2023 02:23:39,01/01/2023 02:23:43,31/12/2022,22:20,A NOITE,01/01/2023,01/01/2023 02:23:39,...,None,None,None,None,FIG8B56,SP,FERRAZ DE VASCONCELO,Vermelho,VW/FOX CONNECT MB,2020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12976,2023.0,552.0,552/2023,31/01/2023 23:05:38,31/01/2023 23:05:38,31/01/2023,19:40,A NOITE,31/01/2023,31/01/2023 23:05:38,...,None,None,None,None,RMT7A75,MG,BELO HORIZONTE,Prata,VW/VOYAGE PLUS,2021.0
12977,2023.0,170023.0,170023/2023,31/01/2023 23:07:03,31/01/2023 23:07:06,31/01/2023,20:17,A NOITE,31/01/2023,31/01/2023 23:07:03,...,None,None,None,None,EBG3309,SP,S.PAULO,Amarelo,FIAT/STILO SPORTING DUAL,2008.0
12978,2023.0,982.0,982/2023,31/01/2023 23:28:40,31/01/2023 23:28:40,31/01/2023,22:25,A NOITE,31/01/2023,31/01/2023 23:28:40,...,None,None,None,None,FUF5D21,SP,S.PAULO,Vermelho,HONDA/CG 160 FAN,2021.0
12979,2023.0,170179.0,170179/2023,31/01/2023 23:47:30,31/01/2023 23:47:33,31/01/2023,21:10,A NOITE,31/01/2023,31/01/2023 23:47:30,...,None,None,GAZ8339,SP,ARUJA,Branco,HONDA/CIVIC EX CVT,2017.0,None,AUTOMOVEL
12980,2023.0,170223.0,170223/2023,31/01/2023 23:57:24,31/01/2023 23:57:28,31/01/2023,19:55,A NOITE,31/01/2023,31/01/2023 23:57:24,...,None,None,GCX3195,SP,S.PAULO,Cinza,FORD/KA,2019.0,None,AUTOMOVEL

In [ ]:
base_sp = base.loc[base['CIDADE'] == "S.PAULO",["ANO_BO","NUM_BO","DATAOCORRENCIA","PERIDOOCORRENCIA","HORAOCORRENCIA","CIDADE_VEICULO","ANO_MODELO"]]
#Filtro de Base de acordo com a cidade e apenas alguns rótulos

In [69]:
display(base_sp)

,ANO_BO,NUM_BO,DATAOCORRENCIA,PERIDOOCORRENCIA,HORAOCORRENCIA,CIDADE_VEICULO,ANO_MODELO
0,2023.0,8696.0,31/12/2022,A NOITE,22:20,FXZ3H05,HONDA/FIT EXL CVT
1,2023.0,70.0,31/12/2022,A TARDE,15:54,FKV8033,I/HONDA CR-V EXL FLEX4WD
7,2023.0,34.0,31/12/2022,A NOITE,23:50,FEY4426,FIAT/DOBLO ADV 1.8 FLEX
9,2023.0,3.0,01/11/2022,A NOITE,22:50,None,None
10,2023.0,3.0,01/11/2022,A NOITE,22:50,QJW6D05,KAWASAKI/VERSYS-X 300 A
...,...,...,...,...,...,...,...
12960,2023.0,155084.0,29/01/2023,A NOITE,20:10,None,None
12961,2023.0,155084.0,29/01/2023,A NOITE,20:10,KZX2105,I/KTM 950 ADVENTURE LC8
12962,2023.0,155084.0,29/01/2023,A NOITE,20:10,None,None
12963,2023.0,155084.0,29/01/2023,A NOITE,20:10,KZX2105,I/KTM 950 ADVENTURE LC8
12975,2023.0,500.0,31/01/2023,A NOITE,21:20,EZB6921,CHEVROLET/CLASSIC LS

In [74]:
type(base_sp.loc[1,'DATAOCORRENCIA'])

str

In [89]:
#base_sp['DIA'] = base_sp['DATAOCORRENCIA'][0:1]

In [90]:
#display(base_sp)

,ANO_BO,NUM_BO,DATAOCORRENCIA,PERIDOOCORRENCIA,HORAOCORRENCIA,CIDADE_VEICULO,ANO_MODELO,DIA
0,2023.0,8696.0,31/12/2022,A NOITE,22:20,FXZ3H05,HONDA/FIT EXL CVT,31/12/2022
1,2023.0,70.0,31/12/2022,A TARDE,15:54,FKV8033,I/HONDA CR-V EXL FLEX4WD,NaN
7,2023.0,34.0,31/12/2022,A NOITE,23:50,FEY4426,FIAT/DOBLO ADV 1.8 FLEX,NaN
9,2023.0,3.0,01/11/2022,A NOITE,22:50,None,None,NaN
10,2023.0,3.0,01/11/2022,A NOITE,22:50,QJW6D05,KAWASAKI/VERSYS-X 300 A,NaN
...,...,...,...,...,...,...,...,...
12960,2023.0,155084.0,29/01/2023,A NOITE,20:10,None,None,NaN
12961,2023.0,155084.0,29/01/2023,A NOITE,20:10,KZX2105,I/KTM 950 ADVENTURE LC8,NaN
12962,2023.0,155084.0,29/01/2023,A NOITE,20:10,None,None,NaN
12963,2023.0,155084.0,29/01/2023,A NOITE,20:10,KZX2105,I/KTM 950 ADVENTURE LC8,NaN
12975,2023.0,500.0,31/01/2023,A NOITE,21:20,EZB6921,CHEVROLET/CLASSIC LS,NaN